### PR TITLE
Correct link to V8 intent to ship

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by ljharb** [comment]
I’m happy to include the direct link, but i chose the tweet link intentionally because that’s the one that’ll be the easiest for mass consumption. Could we keep both?

**Comment by mathiasbynens** [comment]
> that’s the one that’ll be the easiest for mass consumption

Why is that? The tweet is from an unofficial account unaffiliated with the V8 project, and it literally just links to the intent to ship thread. Let’s skip the indirection and point to the actual i2s.

**Comment by ljharb** [comment]
Ah, i didn’t realize it was unofficial - is there an official place its tweeted? The concern here was a lot about the community claiming to be unaware of progress, and people are more likely to keep up with twitter accounts than blogs.

**Review by ljharb — APPROVED** [review]

**Comment by mathiasbynens** [comment]
> Ah, i didn’t realize it was unofficial - is there an official place its tweeted?

No. We don’t generally announce i2s threads. Lots of people subscribe to v8-dev@ or blink-dev@ exactly to get these kind of updates.

**Pull request merged**
